86 create new structure form styling
neotheprogramist/portfolio-management-platform pull request #100
Opened 2024-04-05 14:40 UTC by DariaKozlovska

2024-04-09 20:55 UTC, Uacias approved these changes
LGTM

2024-04-09 20:58 UTC, Uacias commented on package.json
> +    "@types/jquery": "^3.5.29",
Do we need that?

2024-04-10 08:36 UTC, Uacias requested changes

2024-04-10 08:36 UTC, Uacias commented on src/routes/app/portfolio/index.tsx
> +  const isCreateNewStructureModalOpen = useSignal(true);
imo that should be set to false by default

2024-04-10 08:54 UTC, Uacias requested changes

2024-04-10 08:54 UTC, Uacias commented on src/routes/app/portfolio/index.tsx
> +  Signal,
add type

2024-04-10 08:54 UTC, Uacias commented on src/routes/app/portfolio/index.tsx
> +function parseWalletsToOptions(
produces qwik warn

2024-04-10 08:54 UTC, Uacias commented on src/global.css
> +}
nested css produces warn, enable nesting plugin or unnest

2024-04-10 09:05 UTC, Uacias commented on src/global.css
> +}
Possibly to modify in the future, once it produced qwik warn, then vanished

2024-04-10 09:19 UTC, Uacias approved these changes

2024-04-10 09:20 UTC, pgajek approved these changes

2024-04-10 09:20 UTC, merged